include $(TOPDIR)/rules.mk

PKG_VERSION:=2.1.0
PKG_RELEASE:=1
PKG_PO_VERSION:=2.1.0
PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=Modern hardware-aware traffic status
LUCI_DEPENDS:=+luci-base +nlbwmon
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
